# Generated by Django 4.0.2 on 2022-02-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basediscount',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
