# Generated by Django 4.0.2 on 2022-04-03 14:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], default=None, max_length=7, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Enter your phone number', max_length=13, unique=True, validators=[core.validators.check_phone], verbose_name='phone number'),
        ),
    ]
