# Generated by Django 4.0.2 on 2022-04-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_birthdate_user_gender_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
