# Generated by Django 4.0.2 on 2022-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, help_text='Enter your extra description of your address', null=True),
        ),
    ]
