# Generated by Django 4.0.2 on 2022-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email_alter_customer_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alley',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='alley'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='street'),
        ),
    ]
