# Generated by Django 4.0.2 on 2022-04-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_birthdate_customer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
