# Generated by Django 4.0.2 on 2022-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.PositiveIntegerField(default=123456, verbose_name='off code'),
            preserve_default=False,
        ),
    ]
