# Generated by Django 4.0.2 on 2022-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
