# Generated by Django 4.0.2 on 2022-03-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_address_alley_alter_address_city_and_more'),
        ('orders', '0002_alter_offcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customers.address'),
        ),
    ]
