# Generated by Django 4.0.2 on 2022-02-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_offcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.offcode'),
        ),
    ]
