# Generated by Django 4.0.2 on 2022-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_accessories',
            field=models.FileField(help_text='main image', upload_to='products', verbose_name='product accessory image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.FileField(help_text='main image', upload_to='products', verbose_name='product main image'),
        ),
    ]
