# Generated by Django 4.0.2 on 2022-02-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.TextField(blank=True, default=None, help_text='Enter Details of your products', null=True),
        ),
    ]
