# Generated by Django 4.0.2 on 2022-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_accessories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_accessories',
            field=models.FileField(help_text='accessory image', upload_to='products', verbose_name='product accessory image'),
        ),
    ]
