# Generated by Django 4.0.2 on 2022-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
    ]
